project_dir = 'X:/Trans/TIP/Adopted TIPs/2025-28 Working Folder/Call for Projects/FHWA Regional/Scoring/Air Quality/nonmotorized_calcs/data/example_projects.shp'
output_dir = 'outputs'    # Permissions not available to X drive from servers; store outputs elsewhere

parcel_file_dir = 'R:/e2projects_two/SoundCast/Inputs/dev/landuse/2023/base_year/parcels_urbansim.txt'
population_file = 'R:/e2projects_two/SoundCast/Inputs/dev/landuse/2023/base_year/hh_and_persons.h5'

# Spatial projection definitions
LAT_LNG_CRS = 'epsg:4326'    # Survey data expected in lat/lng format
WA_STATE_PLANE_CRS = 'epsg:2285'    # Projection of parcel and TAZ data; survey data is converted to this

buffer_distance = '2640'    # in feet