project_dir = 'X:/Trans/TIP/Adopted TIPs/2025-28 Working Folder/Call for Projects/FHWA Regional/Scoring/Air Quality/nonmotorized_calcs/data/REG_FHWA_Projects.shp'
output_dir = 'outputs'    # Permissions not available to X drive from servers; write outputs locally

ofm_estimate_year = 2023
ofm_vintage = 2023

# Spatial projection definitions
LAT_LNG_CRS = 'epsg:4326'    # Survey data expected in lat/lng format
WA_STATE_PLANE_CRS = 'epsg:2285'    # Projection of parcel and TAZ data; survey data is converted to this

buffer_distance = '2640'    # in feet